sudo: false
language: java
dist: trusty
jdk:
- oraclejdk8
branches:
  only:
  - develop
before_install:
- git clone https://github.com/jcryptool/crypto.git ~/build/jcryptool/crypto
- echo "MAVEN_OPTS=-Xmx2048m" > ~/.mavenrc
install: true
script:
- mvn clean verify -f org.jcryptool.releng/pom.xml -DskipTests=true
before_deploy:
- git config --local user.name "Dominik Schadow"
- git config --local user.email "dominikschadow@gmail.com"
- git tag "Weekly-Build--$(date +'%Y-%m-%d')"
after_success:
# Rename files for better readability
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-linux.gtk.x86_64.tar.gz' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-linux.gtk.x86_64.tar.gz.md5' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz.md5'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-linux.gtk.x86_64.tar.gz.sha1' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz.sha1'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-macosx.cocoa.x86_64.tar.gz' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz'
- mv "org.jcryptool.product/target/products/jcryptool-1.0.0-macosx.cocoa.x86_64.tar.gz.md5' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz.md5'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-macosx.cocoa.x86_64.tar.gz.sha1' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz.sha1'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-win32.win32.x86_64.zip' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip' 
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-win32.win32.x86_64.zip.md5' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip.md5'
- mv 'org.jcryptool.product/target/products/jcryptool-1.0.0-win32.win32.x86_64.zip.sha1' 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip.sha1'
deploy:
  - provider: releases
    prerelease: true
    api_key:
      secure: R/UG294tu6IY7TosmU34/4s2xzSdcUJduZJyQwUC+aGRIm+gSiUniO69MR4KOpStN5EO72RVmEJzFDMe0dpUN8DEoYfSl3ovTWmKF7OTOX/5cCuciR13CT2D8jUU72jws7BIuZbrjggzJWJ79G6zUGo8EyE6xnMoT4ODscT0Emw=
    file:
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip' 
    skip_cleanup: true
    on:
      repo: jcryptool/core
      branch: develop
      condition: "$TRAVIS_EVENT_TYPE = cron"
  - provider: releases
    prerelease: false
    api_key:
      secure: R/UG294tu6IY7TosmU34/4s2xzSdcUJduZJyQwUC+aGRIm+gSiUniO69MR4KOpStN5EO72RVmEJzFDMe0dpUN8DEoYfSl3ovTWmKF7OTOX/5cCuciR13CT2D8jUU72jws7BIuZbrjggzJWJ79G6zUGo8EyE6xnMoT4ODscT0Emw=
    file:
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz.md5'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Linux-64bit.tar.gz.sha1'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz.md5'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-macOS-64bit.tar.gz.sha1'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip' 
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip.md5'
      - 'org.jcryptool.product/target/products/JCrypTool-1.0.0-Windows-64bit.zip.sha1'
    skip_cleanup: true
    on:
      repo: jcryptool/core
      branch: master
      tags: true
